import { sql } from 'drizzle-orm';
import { check, index, integer, primaryKey, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

const timestamps = { createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(), updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull() };
export const user = sqliteTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: integer('email_verified', { mode: 'boolean' }).notNull().default(false), image: text('image'), username: text('username').unique(), displayUsername: text('display_username'), ...timestamps });
export const session = sqliteTable('session', { id: text('id').primaryKey(), expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(), token: text('token').notNull().unique(), createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(), updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(), ipAddress: text('ip_address'), userAgent: text('user_agent'), userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }) }, (table) => [index('session_user_id_idx').on(table.userId)]);
export const account = sqliteTable('account', { id: text('id').primaryKey(), accountId: text('account_id').notNull(), providerId: text('provider_id').notNull(), userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }), accessToken: text('access_token'), refreshToken: text('refresh_token'), idToken: text('id_token'), accessTokenExpiresAt: integer('access_token_expires_at', { mode: 'timestamp_ms' }), refreshTokenExpiresAt: integer('refresh_token_expires_at', { mode: 'timestamp_ms' }), scope: text('scope'), password: text('password'), ...timestamps }, (table) => [index('account_user_id_idx').on(table.userId)]);
export const verification = sqliteTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(), createdAt: integer('created_at', { mode: 'timestamp_ms' }), updatedAt: integer('updated_at', { mode: 'timestamp_ms' }) }, (table) => [index('verification_identifier_idx').on(table.identifier)]);
export const rateLimit = sqliteTable('rate_limit', { id: text('id').primaryKey(), key: text('key').notNull().unique(), count: integer('count').notNull(), lastRequest: integer('last_request').notNull() });

export const appMeta = sqliteTable('app_meta', { key: text('key').primaryKey(), value: text('value').notNull() });
export const blogs = sqliteTable('blogs', {
  id: text('id').primaryKey(), userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }), username: text('username').notNull(),
  hackmdUsername: text('hackmd_username').notNull(), title: text('title'), description: text('description'), author: text('author'),
  state: text('state', { enum: ['syncing', 'ready', 'failed'] }).notNull(), lastError: text('last_error'), draftArtifact: text('draft_artifact'),
  createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull(),
}, (table) => [uniqueIndex('blogs_one_per_user').on(table.userId), uniqueIndex('blogs_username_unique').on(table.username), check('blogs_state_check', sql`${table.state} in ('syncing','ready','failed')`)]);
export const themeRevisions = sqliteTable('theme_revisions', {
  id: text('id').primaryKey(), blogId: text('blog_id').notNull().references(() => blogs.id, { onDelete: 'cascade' }), config: text('config').notNull(), prompt: text('prompt'), description: text('description').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(false), createdAt: text('created_at').notNull(),
}, (table) => [index('theme_revisions_blog_idx').on(table.blogId), uniqueIndex('theme_revisions_one_active').on(table.blogId).where(sql`${table.active} = 1`)]);
export const operations = sqliteTable('operations', {
  id: text('id').primaryKey(), userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }), blogId: text('blog_id').notNull().references(() => blogs.id, { onDelete: 'cascade' }),
  type: text('type', { enum: ['sync', 'generate_theme', 'publish'] }).notNull(), status: text('status', { enum: ['queued', 'running', 'succeeded', 'failed'] }).notNull(), payload: text('payload').notNull(), result: text('result'), errorMessage: text('error_message'), attempts: integer('attempts').notNull().default(0), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull(),
}, (table) => [uniqueIndex('operations_one_active_per_blog').on(table.blogId).where(sql`${table.status} in ('queued','running')`), check('operations_type_check', sql`${table.type} in ('sync','generate_theme','publish')`), check('operations_status_check', sql`${table.status} in ('queued','running','succeeded','failed')`)]);
export const publishedReleases = sqliteTable('published_releases', {
  id: text('id').primaryKey(), blogId: text('blog_id').notNull().references(() => blogs.id, { onDelete: 'cascade' }), themeRevisionId: text('theme_revision_id').notNull().references(() => themeRevisions.id), artifact: text('artifact').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(false), createdAt: text('created_at').notNull(),
}, (table) => [index('published_releases_blog_idx').on(table.blogId), uniqueIndex('published_releases_one_active').on(table.blogId).where(sql`${table.active} = 1`)]);
export const previewSessions = sqliteTable('preview_sessions', { tokenHash: text('token_hash').primaryKey(), userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }), blogId: text('blog_id').notNull().references(() => blogs.id, { onDelete: 'cascade' }), expiresAt: text('expires_at').notNull(), createdAt: text('created_at').notNull() });
export const aiDailyUsage = sqliteTable('ai_daily_usage', { usageDate: text('usage_date').notNull(), scope: text('scope', { enum: ['user', 'global'] }).notNull(), subject: text('subject').notNull(), count: integer('count').notNull().default(0) }, (table) => [primaryKey({ columns: [table.usageDate, table.scope, table.subject] }), check('ai_usage_scope_check', sql`${table.scope} in ('user','global')`), check('ai_usage_count_check', sql`${table.count} >= 0`)]);

export const authSchema = { user, session, account, verification, rateLimit };
