config:
  gcp:project: vibelog-prod-h6t9m2
  vibelog:deploymentPhase: foundation
  vibelog:environment: prod
  vibelog:gcpRegion: asia-east1
  vibelog:cloudflareAccountId: 308b37d37d39bc460bcabc4d5644d365
  vibelog:rootDomain: vibelog.org
  vibelog:minInstances: 0
  vibelog:maxInstances: 3
  vibelog:r2Location: apac
environment:
  - vibelog/prod
