import { SITE_LANGUAGE } from "./consts";

const isTraditionalChinese = SITE_LANGUAGE.toLowerCase().startsWith("zh");

export const text = isTraditionalChinese
  ? {
      skipToContent: "跳至主要內容",
      primaryNavigation: "主要導覽",
      home: "首頁",
      posts: "文章",
      tags: "主題",
      postTags: "文章主題",
      tableOfContents: "文章目錄",
      latestPosts: "最新文章",
      viewAllPosts: "查看所有文章",
      allPosts: "所有文章",
      postsByDate: (count: number) => `${count} 篇文章，依發布日期由新到舊排列。`,
      browseTagsDescription: (siteTitle: string) => `瀏覽 ${siteTitle} 的文章主題。`,
      browseTags: "依主題瀏覽文章。",
      postCount: (count: number) => `${count} 篇`,
      noTags: "目前沒有文章主題。",
      tagDescription: (siteTitle: string, tag: string) => `${siteTitle} 中關於「${tag}」的文章。`,
      tagTitle: (tag: string) => `主題：${tag}`,
      allTags: "所有主題",
      updatedAt: "更新於",
      backToStart: "回到文章開頭",
      postNavigation: "文章導覽",
      newerPost: "較新文章",
      olderPost: "較舊文章",
      notFoundTitle: "找不到頁面",
      notFoundMessage: "這個網址不存在，或內容已經移動。",
      backHome: "返回首頁",
    }
  : {
      skipToContent: "Skip to main content",
      primaryNavigation: "Primary navigation",
      home: "Home",
      posts: "Posts",
      tags: "Topics",
      postTags: "Post topics",
      tableOfContents: "Table of contents",
      latestPosts: "Latest posts",
      viewAllPosts: "View all posts",
      allPosts: "All posts",
      postsByDate: (count: number) => `${count} ${count === 1 ? "post" : "posts"}, newest first.`,
      browseTagsDescription: (siteTitle: string) => `Browse ${siteTitle} posts by topic.`,
      browseTags: "Browse posts by topic.",
      postCount: (count: number) => `${count} ${count === 1 ? "post" : "posts"}`,
      noTags: "No topics yet.",
      tagDescription: (siteTitle: string, tag: string) => `Posts about ${tag} on ${siteTitle}.`,
      tagTitle: (tag: string) => `Topic: ${tag}`,
      allTags: "All topics",
      updatedAt: "Updated",
      backToStart: "Back to article start",
      postNavigation: "Post navigation",
      newerPost: "Newer post",
      olderPost: "Older post",
      notFoundTitle: "Page not found",
      notFoundMessage: "This address does not exist, or the content has moved.",
      backHome: "Back to home",
    };
