import { expect, test } from '@playwright/test';

test('invite signup to hosted publication', async ({ page }) => {
  await page.goto('/auth/register');
  await page.getByLabel('Beta 邀請碼').fill('vibelog-e2e-beta-invite-code');
  await page.getByLabel('Username').fill('alice');
  await page.getByLabel('密碼').fill('a-long-enough-test-password');
  await page.getByRole('button', { name: '建立帳號' }).click();
  await expect(page).toHaveURL(/\/onboarding$/);

  await page.getByLabel('HackMD username').fill('missing-hackmd');
  const initialSync = page.getByRole('button', { name: '同步並建立預覽' });
  await initialSync.click();
  await expect(page.getByText('找不到這個公開 HackMD 使用者')).toBeVisible({ timeout: 30_000 });
  await expect(initialSync).toBeEnabled();
  await expect(page.locator('form[action="/actions/blog/connect"]')).not.toHaveAttribute('aria-busy');
  await expect(page).toHaveURL(/\/onboarding$/);
  await page.getByLabel('HackMD username').fill('alice-hackmd');
  await page.getByRole('button', { name: '同步並建立預覽' }).click();
  await expect(page).toHaveURL(/\/editor$/, { timeout: 120_000 });
  await expect(page.getByText('尚未發布', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  const mobileControls = await page.locator('.controls').boundingBox();
  const mobilePreview = await page.locator('.preview-panel').boundingBox();
  expect(mobileControls?.y).toBeLessThan(mobilePreview?.y ?? 0);
  await page.setViewportSize({ width: 1280, height: 900 });
  const desktopControls = await page.locator('.controls').boundingBox();
  const desktopPreview = await page.locator('.preview-panel').boundingBox();
  expect(desktopControls?.x).toBeLessThan(desktopPreview?.x ?? 0);
  await expect(page.getByText('已匯入文章（2） · 已選取 2')).toBeVisible();
  await page.getByText('已匯入文章（2） · 已選取 2').click();
  await expect(page.getByText('Hello VibeLog', { exact: true })).toBeVisible();
  await page.getByLabel('Archive Note').uncheck();
  await page.getByRole('button', { name: '儲存文章選擇並重建草稿' }).click();
  await expect(page.getByText('已匯入文章（2） · 已選取 1')).toBeVisible({ timeout: 120_000 });
  const preview = page.frameLocator('iframe[title*="即時預覽"]');
  await expect(preview.getByRole('heading', { name: "Alice Writer's blog", exact: true })).toBeVisible({ timeout: 30_000 });
  expect((await page.request.get('http://preview.app.localtest.me:3100/blog/archive-note/')).status()).toBe(404);

  await page.getByLabel('Blog 標題').fill('Alice’s Field Notes');
  await page.getByLabel('Blog 描述').fill('Notes about humane software and careful tools.');
  await page.getByRole('button', { name: '儲存並重建草稿' }).click();
  await expect(page.getByRole('heading', { name: 'Alice’s Field Notes', exact: true })).toBeVisible({ timeout: 120_000 });
  await expect(preview.getByRole('link', { name: 'Alice’s Field Notes', exact: true })).toBeVisible({ timeout: 30_000 });

  await page.getByRole('button', { name: '重新同步 HackMD' }).click();
  await expect(page.getByText('已匯入文章（3） · 已選取 2')).toBeVisible({ timeout: 120_000 });
  await page.getByText('已匯入文章（3） · 已選取 2').click();
  await expect(page.getByLabel('Archive Note')).not.toBeChecked();
  await expect(page.getByLabel('Newly Synced Note')).toBeChecked();

  await page.getByText('手動微調安全樣式').click();
  await page.getByLabel('Editorial').check();
  await page.getByLabel('Newsprint').check();
  await page.getByLabel('Centered').check();
  await page.getByLabel('Numbered').check();
  await page.getByLabel('Panel').check();
  await expect(page.getByText('預覽已更新，尚未儲存', { exact: true })).toBeVisible({ timeout: 30_000 });
  await expect(page.getByText('這些樣式尚未儲存；儲存後才能發布。')).toBeVisible();
  await expect(page.getByRole('button', { name: /發布第一版到/ })).toBeDisabled();
  await page.getByRole('button', { name: '儲存成新版本' }).click();
  await expect(page).toHaveURL(/\/editor$/);
  await page.getByText(/歷史樣式/).click();
  await expect(page.getByText('Editorial · Newsprint · Sans / Sans · Medium · Centered header · Numbered list · Code panel')).toBeVisible();
  await expect(page.getByText('手動', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: /發布第一版到/ }).click();
  await expect(page.getByText('已與線上版本同步', { exact: true })).toBeVisible({ timeout: 30_000 });

  await page.getByLabel('描述你想要的感覺').fill('像一本溫暖而克制的獨立雜誌');
  await page.getByRole('button', { name: '交給 AI 設計' }).click();
  await expect(page.getByText('有未發布變更', { exact: true })).toBeVisible({ timeout: 30_000 });
  await page.getByText(/歷史樣式/).click();
  await expect(page.getByText('A warm editorial theme.')).toBeVisible({ timeout: 30_000 });
  await expect(page.getByText('預覽中', { exact: true })).toBeVisible();

  await page.getByRole('button', { name: /發布變更到/ }).click();
  await expect(page.getByText('已與線上版本同步', { exact: true })).toBeVisible({ timeout: 30_000 });
  await expect(page.getByRole('button', { name: /已是最新版本/ })).toBeDisabled();
  await expect(page.getByRole('link', { name: '查看已發布網站' })).toBeVisible({ timeout: 30_000 });
  const aiCss = await (await page.request.get('http://alice.app.localtest.me:3100/theme.css')).text();
  await page.getByText('發布紀錄（2）', { exact: true }).click();
  await expect(page.getByText('目前線上', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '還原為線上版本' }).click();
  await expect(page.getByText('有未發布變更', { exact: true })).toBeVisible();
  const restoredCss = await (await page.request.get('http://alice.app.localtest.me:3100/theme.css')).text();
  expect(restoredCss).not.toBe(aiCss);
  await page.getByText('發布紀錄（2）', { exact: true }).click();
  await page.getByRole('button', { name: '還原為線上版本' }).click();
  await expect(page.getByText('已與線上版本同步', { exact: true })).toBeVisible();
  const publicResponse = await page.request.get('http://alice.app.localtest.me:3100/');
  expect(publicResponse.headers()['content-security-policy']).toContain("script-src 'none'");
  await page.goto('http://alice.app.localtest.me:3100/');
  await page.keyboard.press('Tab');
  await expect(page.getByRole('link', { name: '跳至主要內容' })).toBeFocused();
  await expect(page.getByRole('heading', { name: 'Alice’s Field Notes', exact: true })).toBeVisible();
  await expect(page.getByText('Alice Writer', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '最新文章' })).toBeVisible();
  await expect(page.getByRole('link', { name: '查看所有文章' })).toBeVisible();
  await expect(page).toHaveTitle('Alice’s Field Notes');
  await expect(page.locator('meta[property="og:title"]')).toHaveAttribute('content', 'Alice’s Field Notes');
  await expect(page.locator('meta[name="description"]')).toHaveAttribute('content', 'Notes about humane software and careful tools.');
  await page.goto('http://alice.app.localtest.me:3100/blog/hello-vibelog/');
  await expect(page.getByRole('heading', { name: 'Hello VibeLog' })).toBeVisible();
  await expect(page).toHaveTitle('Hello VibeLog · Alice’s Field Notes');
  await expect(page.locator('meta[property="og:type"]')).toHaveAttribute('content', 'article');
  await expect(page.locator('meta[property="article:published_time"]')).toHaveAttribute('content', '2026-07-19T00:00:00.000Z');
  await expect(page.getByRole('link', { name: /較新文章 Newly Synced Note/ })).toBeVisible();
  expect((await page.request.get('http://alice.app.localtest.me:3100/blog/archive-note/')).status()).toBe(404);
  expect((await page.request.get('http://alice.app.localtest.me:3100/blog/newly-synced-note/')).status()).toBe(200);
  const rss = await page.request.get('http://alice.app.localtest.me:3100/rss.xml');
  const rssText = await rss.text();
  expect(rssText).toContain('<title>Alice’s Field Notes</title>');
  expect(rssText).not.toContain('Archive Note');
  expect(rssText).toContain('Newly Synced Note');
  expect(rssText).toContain('<pubDate>Mon, 20 Jul 2026 00:00:00 GMT</pubDate>');
  const sitemap = await (await page.request.get('http://alice.app.localtest.me:3100/sitemap-0.xml')).text();
  expect(sitemap).not.toContain('/blog/archive-note/');
  expect(sitemap).toContain('/blog/newly-synced-note/');

  await page.goto('http://app.localtest.me:3100/editor');
  await page.getByText('已匯入文章（3） · 已選取 2').click();
  await page.getByLabel('Archive Note').check();
  await page.getByRole('button', { name: '儲存文章選擇並重建草稿' }).click();
  await expect(page.getByText('有未發布變更', { exact: true })).toBeVisible({ timeout: 120_000 });
  await page.getByRole('button', { name: /發布變更到/ }).click();
  await expect(page.getByText('已與線上版本同步', { exact: true })).toBeVisible({ timeout: 30_000 });
  expect((await page.request.get('http://alice.app.localtest.me:3100/blog/archive-note/')).status()).toBe(200);
  expect(await (await page.request.get('http://alice.app.localtest.me:3100/rss.xml')).text()).toContain('Archive Note');
});
