import { expect, test } from '@playwright/test';

test('public signup to hosted publication', async ({ page }) => {
  const articleDescription = 'This is reliable public prose with readable text and code.';
  await page.route('https://images.example.com/**', (route) => route.abort());
  await page.goto('/');
  const primaryCta = page.getByRole('link', { name: 'Create your blog' });
  await expect(primaryCta).toHaveCSS('color', 'rgb(255, 255, 255)');
  await page.getByRole('link', { name: 'Guide' }).click();
  await expect(page.getByRole('heading', { name: 'From HackMD to your own blog' })).toBeVisible();
  await page.getByRole('link', { name: 'Create your blog' }).click();
  await page.getByLabel('Username').fill('alice');
  await page.getByLabel('Password').fill('a-long-enough-test-password');
  await page.getByRole('button', { name: 'Create account' }).click();
  await expect(page).toHaveURL(/\/onboarding$/);

  await page.getByLabel('HackMD username').fill('missing-hackmd');
  await page.getByLabel('Blog language').fill('en-US');
  const initialSync = page.getByRole('button', { name: 'Sync and build preview' });
  await initialSync.click();
  await expect(page.getByText('We could not find that public HackMD user')).toBeVisible({ timeout: 30_000 });
  await expect(initialSync).toBeEnabled();
  await expect(page.locator('form[action="/actions/blog/connect"]')).not.toHaveAttribute('aria-busy');
  await expect(page).toHaveURL(/\/onboarding$/);
  await page.getByLabel('HackMD username').fill('alice-hackmd');
  await page.getByRole('button', { name: 'Sync and build preview' }).click();
  await expect(page).toHaveURL(/\/editor$/, { timeout: 120_000 });
  await expect(page.getByText('Not published', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  const mobileControls = await page.locator('.controls').boundingBox();
  const mobilePreview = await page.locator('.preview-panel').boundingBox();
  expect(mobileControls?.y).toBeLessThan(mobilePreview?.y ?? 0);
  await page.setViewportSize({ width: 1280, height: 900 });
  const desktopControls = await page.locator('.controls').boundingBox();
  const desktopPreview = await page.locator('.preview-panel').boundingBox();
  expect(desktopControls?.x).toBeLessThan(desktopPreview?.x ?? 0);
  await expect(page.getByText('Imported articles (2) · 2 selected')).toBeVisible();
  await page.getByText('Imported articles (2) · 2 selected').click();
  await expect(page.getByText('Hello VibeLog', { exact: true })).toBeVisible();
  await expect(page.getByText('Product', { exact: true })).toBeVisible();
  await expect(page.locator('.content-choice', { hasText: 'Hello VibeLog' })).toContainText('Updated');
  await page.getByLabel('Archive Note').uncheck();
  await page.getByRole('button', { name: 'Save selection and rebuild draft' }).click();
  await expect(page.getByText('Imported articles (2) · 1 selected')).toBeVisible({ timeout: 120_000 });
  const preview = page.frameLocator('iframe[title*="Live preview"]');
  await expect(preview.getByRole('heading', { name: "Alice Writer's blog", exact: true })).toBeVisible({ timeout: 30_000 });
  await expect(preview.getByText(articleDescription, { exact: true })).toBeVisible();
  expect((await page.request.get('http://preview.app.localtest.me:3100/blog/archive-note/')).status()).toBe(404);
  const previewArticle = await page.request.get('http://preview.app.localtest.me:3100/blog/hello-vibelog/');
  expect(previewArticle.status()).toBe(200);
  const previewArticleHtml = await previewArticle.text();
  expect(previewArticleHtml).toContain('aria-label="Table of contents"');
  expect(previewArticleHtml).toContain('href="#implementation-details"');

  await page.getByLabel('Blog title').fill('Alice’s Field Notes');
  await page.getByLabel('Blog description').fill('Notes about humane software and careful tools.');
  await page.getByRole('button', { name: 'Save and rebuild draft' }).click();
  await expect(page.getByRole('heading', { name: 'Alice’s Field Notes', exact: true })).toBeVisible({ timeout: 120_000 });
  await expect(preview.getByRole('link', { name: 'Alice’s Field Notes', exact: true })).toBeVisible({ timeout: 30_000 });
  await expect(preview.getByRole('link', { name: 'Topics', exact: true })).toBeVisible();
  expect((await page.request.get('http://preview.app.localtest.me:3100/tags/product/')).status()).toBe(200);
  expect((await page.request.get('http://preview.app.localtest.me:3100/tags/archive/')).status()).toBe(404);

  await page.getByRole('button', { name: 'Sync HackMD again' }).click();
  await expect(page.getByText('Imported articles (3) · 2 selected')).toBeVisible({ timeout: 120_000 });
  await page.getByText('Imported articles (3) · 2 selected').click();
  await expect(page.getByLabel('Archive Note')).not.toBeChecked();
  await expect(page.getByLabel('Newly Synced Note')).toBeChecked();

  await page.getByText('Adjust safe theme controls').click();
  await page.getByLabel('Editorial').check();
  await page.getByLabel('Newsprint').check();
  await page.getByLabel('Centered').check();
  await page.getByLabel('Numbered').check();
  await page.getByLabel('Panel').check();
  await expect(page.getByText('Preview updated; changes are not saved', { exact: true })).toBeVisible({ timeout: 30_000 });
  await expect(page.getByText('These theme changes are not saved. Save before publishing.')).toBeVisible();
  await expect(page.getByRole('button', { name: /Publish first release to/ })).toBeDisabled();
  await page.getByRole('button', { name: 'Save as a new version' }).click();
  await expect(page).toHaveURL(/\/editor$/);
  await page.getByText(/Theme history/).click();
  await expect(page.locator('.revision strong').getByText('Editorial · Newsprint · Sans / Sans · Medium · Centered header · Numbered list · Code panel', { exact: true })).toBeVisible();
  await expect(page.getByText('Manual', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: /Publish first release to/ }).click();
  await expect(page.getByText('Live version is current', { exact: true })).toBeVisible({ timeout: 30_000 });

  await page.getByLabel('Describe the feel you want').fill('A warm but restrained independent magazine');
  await page.getByRole('button', { name: 'Generate with AI' }).click();
  await expect(page.getByText('Unpublished changes', { exact: true })).toBeVisible({ timeout: 30_000 });
  await expect(page.locator('.publication-summary').getByText('Theme', { exact: true })).toBeVisible();
  await page.getByText(/Theme history/).click();
  await expect(page.locator('.revision strong').getByText('A warm editorial theme.', { exact: true })).toBeVisible({ timeout: 30_000 });
  await expect(page.getByText('Previewing', { exact: true })).toBeVisible();

  await page.getByRole('button', { name: /Publish changes to/ }).click();
  await expect(page.getByText('Live version is current', { exact: true })).toBeVisible({ timeout: 30_000 });
  await expect(page.getByText('There are no unpublished changes.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: /Already current/ })).toBeDisabled();
  await expect(page.getByRole('link', { name: 'View published site' })).toBeVisible({ timeout: 30_000 });
  const aiCss = await (await page.request.get('http://alice.app.localtest.me:3100/theme.css')).text();
  await page.getByText('Release history (2/20)', { exact: true }).click();
  await expect(page.getByText('Live now', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Restore as live' }).click();
  await expect(page.getByText('Unpublished changes', { exact: true })).toBeVisible();
  const restoredCss = await (await page.request.get('http://alice.app.localtest.me:3100/theme.css')).text();
  expect(restoredCss).not.toBe(aiCss);
  await page.getByText('Release history (2/20)', { exact: true }).click();
  await page.getByRole('button', { name: 'Restore as live' }).click();
  await expect(page.getByText('Live version is current', { exact: true })).toBeVisible();
  const publicResponse = await page.request.get('http://alice.app.localtest.me:3100/');
  expect(await publicResponse.text()).toContain('<html lang="en-US">');
  expect(publicResponse.headers()['content-security-policy']).toContain("script-src 'none'");
  await page.goto('http://alice.app.localtest.me:3100/');
  await page.keyboard.press('Tab');
  await expect(page.getByRole('link', { name: 'Skip to main content' })).toBeFocused();
  await expect(page.getByRole('heading', { name: 'Alice’s Field Notes', exact: true })).toBeVisible();
  await expect(page.getByText('Alice Writer', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Latest posts' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'View all posts' })).toBeVisible();
  await expect(page.getByText(articleDescription, { exact: true })).toBeVisible();
  await expect(page).toHaveTitle('Alice’s Field Notes');
  await expect(page.locator('meta[property="og:title"]')).toHaveAttribute('content', 'Alice’s Field Notes');
  await expect(page.locator('meta[name="description"]')).toHaveAttribute('content', 'Notes about humane software and careful tools.');
  await page.goto('http://alice.app.localtest.me:3100/blog/hello-vibelog/');
  await expect(page.getByRole('heading', { name: 'Hello VibeLog' })).toBeVisible();
  await expect(page).toHaveTitle('Hello VibeLog · Alice’s Field Notes');
  await expect(page.locator('meta[property="og:type"]')).toHaveAttribute('content', 'article');
  await expect(page.locator('meta[name="description"]')).toHaveAttribute('content', articleDescription);
  await expect(page.locator('meta[property="og:description"]')).toHaveAttribute('content', articleDescription);
  await expect(page.locator('meta[property="article:published_time"]')).toHaveAttribute('content', '2026-07-19T00:00:00.000Z');
  await expect(page.locator('meta[property="article:modified_time"]')).toHaveAttribute('content', '2026-07-21T12:00:00.000Z');
  await expect(page.locator('meta[property="article:tag"]')).toHaveCount(2);
  await expect(page.locator('.blog-post-update')).toContainText('Updated');
  await expect(page.getByRole('link', { name: /Newer post Newly Synced Note/ })).toBeVisible();
  const tableOfContents = page.getByRole('navigation', { name: 'Table of contents' });
  await expect(tableOfContents).toBeVisible();
  const disclosure = tableOfContents.locator('details');
  const summary = tableOfContents.locator('summary');
  await expect(disclosure).toHaveAttribute('open', '');
  await summary.focus();
  await page.keyboard.press('Space');
  await expect(disclosure).not.toHaveAttribute('open', '');
  await page.keyboard.press('Enter');
  await expect(disclosure).toHaveAttribute('open', '');
  await tableOfContents.getByRole('link', { name: 'Implementation details' }).click();
  await expect(page).toHaveURL(/#implementation-details$/);
  await expect(page.locator('#implementation-details')).toBeVisible();
  await page.getByRole('link', { name: 'Back to article start' }).click();
  await expect(page).toHaveURL(/#article-start$/);
  expect((await page.request.get('http://alice.app.localtest.me:3100/blog/archive-note/')).status()).toBe(404);
  expect((await page.request.get('http://alice.app.localtest.me:3100/blog/newly-synced-note/')).status()).toBe(200);
  const rss = await page.request.get('http://alice.app.localtest.me:3100/rss.xml');
  const rssText = await rss.text();
  expect(rssText).toContain('<title>Alice’s Field Notes</title>');
  expect(rssText).toContain('<language>en-US</language>');
  expect(rssText).not.toContain('Archive Note');
  expect(rssText).toContain('Newly Synced Note');
  expect(rssText).toContain('<pubDate>Mon, 20 Jul 2026 00:00:00 GMT</pubDate>');
  expect(rssText).toContain('<category>Product</category>');
  expect(rssText).toContain(`<description>${articleDescription}</description>`);
  expect(rssText).not.toContain('images.example.com');
  const sitemap = await (await page.request.get('http://alice.app.localtest.me:3100/sitemap-0.xml')).text();
  expect(sitemap).not.toContain('/blog/archive-note/');
  expect(sitemap).toContain('/blog/newly-synced-note/');
  expect(sitemap).toContain('/tags/product/');
  await page.goto('http://alice.app.localtest.me:3100/tags/product/');
  await expect(page.getByRole('heading', { name: 'Product' })).toBeVisible();
  await expect(page.getByRole('link', { name: /Newly Synced Note/ })).toBeVisible();
  await expect(page.getByRole('link', { name: /Hello VibeLog/ })).toBeVisible();
  await expect(page.getByText(articleDescription, { exact: true })).toBeVisible();

  await page.goto('http://app.localtest.me:3100/editor');
  await page.getByRole('button', { name: 'Sync HackMD again' }).click();
  await expect(page.getByText('Imported articles (4) · 3 selected')).toBeVisible({ timeout: 120_000 });
  const publicationSummary = page.locator('.publication-summary');
  const publicationBadges = publicationSummary.locator('.publication-badges');
  await expect(publicationBadges.getByText('Added 1', { exact: true })).toBeVisible();
  await expect(publicationBadges.getByText('Updated 1', { exact: true })).toBeVisible();
  await page.getByText('Imported articles (4) · 3 selected').click();
  await page.getByLabel('Newly Synced Note').uncheck();
  await page.getByRole('button', { name: 'Save selection and rebuild draft' }).click();
  await expect(page.getByText('Unpublished changes', { exact: true })).toBeVisible({ timeout: 120_000 });
  await expect(publicationBadges.getByText('Added 1', { exact: true })).toBeVisible();
  await expect(publicationBadges.getByText('Updated 1', { exact: true })).toBeVisible();
  await expect(publicationBadges.getByText('Removed 1', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: /Publish changes to/ }).click();
  await expect(page.getByText('Live version is current', { exact: true })).toBeVisible({ timeout: 30_000 });
  await expect(page.getByText('There are no unpublished changes.', { exact: true })).toBeVisible();
  expect((await page.request.get('http://alice.app.localtest.me:3100/blog/archive-note/')).status()).toBe(404);
  expect((await page.request.get('http://alice.app.localtest.me:3100/blog/newly-synced-note/')).status()).toBe(404);
  expect((await page.request.get('http://alice.app.localtest.me:3100/blog/after-publish-note/')).status()).toBe(200);
  const finalRss = await (await page.request.get('http://alice.app.localtest.me:3100/rss.xml')).text();
  expect(finalRss).toContain('After Publish Note');
  expect(finalRss).not.toContain('Newly Synced Note');
});
